apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-7csa
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-7csa
    app.kubernetes.io/part-of: my-app
  name: devfile-sample-7csa
  namespace: jduimovich-tenant
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nodejs-app
      app.kubernetes.io/instance: devfile-sample-7csa
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-app
        app.kubernetes.io/instance: devfile-sample-7csa
    spec:
      containers:
      - image: quay.io/redhat-appstudio/user-workload@sha256:005aa05e28f8ca47428688c96b4cde00d6d4627cbd680bddc252bdeef2c0bb55
        name: my-nodejs
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 100m
            memory: 100Mi
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
